import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { getCachedClient } from '@/sanity/lib/getClient';
import { siteConfigQuery } from '@/sanity/lib/queries';
import FooterProduct from '@/components/FooterProduct';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next sanity starter',
  description: 'Generated by create next app',
};

export default async function Layout({ children }: { children: React.ReactNode }) {
  const config = await getCachedClient(undefined)(siteConfigQuery);

  return (
    <>
      <Navbar />
      {children}
      <FooterProduct />
    </>
  );
}
