import './globals.css';

export const metadata = {
  title: 'My Awesome Site',
  description: 'Generated by Next + Sanity',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="max-w-full max-h-screen mx-auto">
        <main className="">{children}</main>
      </body>
    </html>
  );
}
